### ISSUE TITLE
SQL Error on install

### ISSUE THREAD

**Issue by xwmario** [WildcardSearch/YourCode#50]
```
SQL Error:
1366 - Incorrect integer value: 'NULL' for column 'sid' at row 1
Query:
INSERT INTO mybb_settings (`sid`,`name`,`title`,`description`,`optionscode`,`value`,`disporder`,`gid`) VALUES ('NULL','yourcode_minimize_js','Minimize JavaScript?','YES (default) to serve client-side scripts minified to increase performance, NO to serve beautiful, commented code ;)','yesno','1','10',45)
```

This is the current error i am getting on a fresh install. any way to bypass it or solve it @WildcardSearch ?

**Comment by WildcardSearch** [comment]
That's odd, @xwmario. I could have sworn I already fixed this...

The workaround is to remove this line:

https://github.com/WildcardSearch/YourCode/blob/b8eaddeca45c8dfe8a8121437cc9f3c09a91de85/Upload/inc/plugins/yourcode/install_data.php#L70

I'll tag this and try to get it fixed in the next version. Thanks for the report.

**Comment by xwmario** [comment]
Hey, thanks for the awesome and fast response. I tried the workaround but this is the error which i am getting.
```
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1366 - Incorrect integer value: '' for column 'nestable' at row 1
Query:
INSERT INTO mybb_yourcode (`title`,`description`,`parse_order`,`nestable`,`active`,`case_sensitive`,`single_line`,`multi_line`,`eval`,`callback`,`regex`,`replacement`,`alt_replacement`,`can_use`,`can_view`,`default_id`,`dateline`) VALUES ('Format - Bold','MyBB Default Bold MyCode',10,'','1','','1','','','','\\[b\\](.*?)\\[/b\\]','<span style=\"font-weight: bold;\" class=\"mycode_b\">$1</span>','','','',1,1571516902)
Please contact the MyBB Group for technical support.
```

**Comment by WildcardSearch** [comment]
Let me look at it tomorrow and I'll get back with you.

**Comment by xwmario** [comment]
Hello,
Just curious to know when the fix will be released

Warm regards.

**Comment by WildcardSearch** [comment]
So sorry. I have been really busy lately. I will try to get this done as soon as I can.

**Comment by Chlorel** [comment]
See time walk's away ... but problem's till the same ...
We are at October 11 year 2023 
Got the last official release for YourCode on myBB home page
Try to install and ... oh surprise ... i got 

[Wed Oct 11 05:15:07.359950 2023] [php:error] [pid 255019] PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect integer value: 'NULL' for column 'sid' at row 1 in /var/www/myBB/inc/db_mysqli.php:335\nStack trace:\n#0 /var/www/myBB/inc/db_mysqli.php(335): mysqli_query()\n#1 /var/www/myBB/inc/db_mysqli.php(378): DB_MySQLi->query()\n#2 /var/www/myBB/inc/db_mysqli.php(889): DB_MySQLi->write_query()\n#3 /var/www/myBB/inc/plugins/yourcode/classes/WildcardPluginInstaller020000.php(393): DB_MySQLi->insert_query_multiple()\n#4 /var/www/myBB/inc/plugins/yourcode/classes/WildcardPluginInstaller020000.php(195): WildcardPluginInstaller020000->addSettings()\n#5 /var/www/myBB/inc/plugins/yourcode/install.php(131): WildcardPluginInstaller020000->install()\n#6 /var/www/myBB/admin/modules/config/plugins.php(432): yourcode_install()\n#7 /var/www/myBB/admin/index.php(830): require('...')\n#8 {main}\n  thrown in /var/www/myBB/inc/db_mysqli.php on line 335

well to fix this it is simple
open /inc/plugins/yourcode/install_data.php
go to line 70 and replace : "sid" => 'NULL',  with : "sid" => '0',
